/**
 * pkgui — Package Manager Registry
 * Covers 40+ package managers across all major OS families
 */

export const OS_FAMILIES = {
  linux: 'Linux',
  macos: 'macOS',
  windows: 'Windows',
  bsd: 'BSD',
  unix: 'Unix/Other',
  cross: 'Cross-platform',
  lang: 'Language-specific',
}

export const PACKAGE_MANAGERS = [
  // ─── DEBIAN / UBUNTU ─────────────────────────────────────────────────────
  {
    id: 'apt',
    name: 'APT',
    fullName: 'Advanced Package Tool',
    os: ['linux'],
    distros: ['Debian', 'Ubuntu', 'Mint', 'Kali', 'Pop!_OS', 'Raspberry Pi OS'],
    icon: '🐧',
    color: '#c24e1e',
    detectCmd: 'which apt',
    detectFile: '/usr/bin/apt',
    commands: {
      install: (pkg) => `sudo apt install ${pkg}`,
      remove: (pkg) => `sudo apt remove ${pkg}`,
      update: () => `sudo apt update`,
      upgrade: () => `sudo apt upgrade`,
      search: (pkg) => `apt search ${pkg}`,
      info: (pkg) => `apt show ${pkg}`,
      list: () => `apt list --installed`,
      clean: () => `sudo apt autoremove && sudo apt clean`,
    },
    homepage: 'https://wiki.debian.org/Apt',
  },
  {
    id: 'dpkg',
    name: 'dpkg',
    fullName: 'Debian Package Manager',
    os: ['linux'],
    distros: ['Debian', 'Ubuntu'],
    icon: '📦',
    color: '#a80030',
    detectCmd: 'which dpkg',
    commands: {
      install: (pkg) => `sudo dpkg -i ${pkg}.deb`,
      remove: (pkg) => `sudo dpkg -r ${pkg}`,
      search: (pkg) => `dpkg -l | grep ${pkg}`,
      info: (pkg) => `dpkg -s ${pkg}`,
      list: () => `dpkg -l`,
    },
    homepage: 'https://wiki.debian.org/dpkg',
  },

  // ─── RED HAT FAMILY ───────────────────────────────────────────────────────
  {
    id: 'dnf',
    name: 'DNF',
    fullName: 'Dandified YUM',
    os: ['linux'],
    distros: ['Fedora', 'RHEL', 'CentOS Stream', 'AlmaLinux', 'Rocky Linux'],
    icon: '🎩',
    color: '#e00',
    detectCmd: 'which dnf',
    commands: {
      install: (pkg) => `sudo dnf install ${pkg}`,
      remove: (pkg) => `sudo dnf remove ${pkg}`,
      update: () => `sudo dnf check-update`,
      upgrade: () => `sudo dnf upgrade`,
      search: (pkg) => `dnf search ${pkg}`,
      info: (pkg) => `dnf info ${pkg}`,
      list: () => `dnf list installed`,
      clean: () => `sudo dnf autoremove && sudo dnf clean all`,
    },
    homepage: 'https://rpm-software-management.github.io/dnf/',
  },
  {
    id: 'yum',
    name: 'YUM',
    fullName: 'Yellowdog Updater Modified',
    os: ['linux'],
    distros: ['RHEL 7', 'CentOS 7', 'Oracle Linux'],
    icon: '🟡',
    color: '#c8a200',
    detectCmd: 'which yum',
    commands: {
      install: (pkg) => `sudo yum install ${pkg}`,
      remove: (pkg) => `sudo yum remove ${pkg}`,
      update: () => `sudo yum check-update`,
      upgrade: () => `sudo yum update`,
      search: (pkg) => `yum search ${pkg}`,
      info: (pkg) => `yum info ${pkg}`,
      list: () => `yum list installed`,
      clean: () => `sudo yum autoremove && sudo yum clean all`,
    },
    homepage: 'http://yum.baseurl.org/',
  },
  {
    id: 'rpm',
    name: 'RPM',
    fullName: 'RPM Package Manager',
    os: ['linux'],
    distros: ['RHEL', 'Fedora', 'SUSE', 'openSUSE'],
    icon: '🔴',
    color: '#e00',
    detectCmd: 'which rpm',
    commands: {
      install: (pkg) => `sudo rpm -ivh ${pkg}.rpm`,
      remove: (pkg) => `sudo rpm -e ${pkg}`,
      info: (pkg) => `rpm -qi ${pkg}`,
      list: () => `rpm -qa`,
      search: (pkg) => `rpm -qa | grep ${pkg}`,
    },
    homepage: 'https://rpm.org/',
  },
  {
    id: 'zypper',
    name: 'zypper',
    fullName: 'ZYpp Package Manager',
    os: ['linux'],
    distros: ['openSUSE', 'SUSE Linux Enterprise'],
    icon: '🦎',
    color: '#73ba25',
    detectCmd: 'which zypper',
    commands: {
      install: (pkg) => `sudo zypper install ${pkg}`,
      remove: (pkg) => `sudo zypper remove ${pkg}`,
      update: () => `sudo zypper refresh`,
      upgrade: () => `sudo zypper update`,
      search: (pkg) => `zypper search ${pkg}`,
      info: (pkg) => `zypper info ${pkg}`,
      list: () => `zypper packages --installed-only`,
    },
    homepage: 'https://en.opensuse.org/Portal:Zypper',
  },

  // ─── ARCH FAMILY ─────────────────────────────────────────────────────────
  {
    id: 'pacman',
    name: 'pacman',
    fullName: 'Pacman Package Manager',
    os: ['linux'],
    distros: ['Arch Linux', 'Manjaro', 'EndeavourOS', 'Garuda', 'Artix'],
    icon: '🎮',
    color: '#1793d1',
    detectCmd: 'which pacman',
    commands: {
      install: (pkg) => `sudo pacman -S ${pkg}`,
      remove: (pkg) => `sudo pacman -R ${pkg}`,
      update: () => `sudo pacman -Sy`,
      upgrade: () => `sudo pacman -Syu`,
      search: (pkg) => `pacman -Ss ${pkg}`,
      info: (pkg) => `pacman -Si ${pkg}`,
      list: () => `pacman -Q`,
      clean: () => `sudo pacman -Rns $(pacman -Qtdq)`,
    },
    homepage: 'https://archlinux.org/pacman/',
  },
  {
    id: 'yay',
    name: 'yay',
    fullName: 'Yet Another Yaourt (AUR Helper)',
    os: ['linux'],
    distros: ['Arch Linux', 'Manjaro'],
    icon: '⚡',
    color: '#1793d1',
    detectCmd: 'which yay',
    commands: {
      install: (pkg) => `yay -S ${pkg}`,
      remove: (pkg) => `yay -R ${pkg}`,
      update: () => `yay -Sy`,
      upgrade: () => `yay -Syu`,
      search: (pkg) => `yay -Ss ${pkg}`,
      info: (pkg) => `yay -Si ${pkg}`,
      list: () => `yay -Q`,
    },
    homepage: 'https://github.com/Jguer/yay',
  },

  // ─── ALPINE ───────────────────────────────────────────────────────────────
  {
    id: 'apk',
    name: 'apk',
    fullName: 'Alpine Package Keeper',
    os: ['linux'],
    distros: ['Alpine Linux'],
    icon: '🏔️',
    color: '#0d597f',
    detectCmd: 'which apk',
    commands: {
      install: (pkg) => `apk add ${pkg}`,
      remove: (pkg) => `apk del ${pkg}`,
      update: () => `apk update`,
      upgrade: () => `apk upgrade`,
      search: (pkg) => `apk search ${pkg}`,
      info: (pkg) => `apk info ${pkg}`,
      list: () => `apk list --installed`,
      clean: () => `apk cache clean`,
    },
    homepage: 'https://wiki.alpinelinux.org/wiki/Alpine_Package_Keeper',
  },

  // ─── VOID LINUX ──────────────────────────────────────────────────────────
  {
    id: 'xbps',
    name: 'xbps',
    fullName: 'X Binary Package System',
    os: ['linux'],
    distros: ['Void Linux'],
    icon: '🌀',
    color: '#478061',
    detectCmd: 'which xbps-install',
    commands: {
      install: (pkg) => `sudo xbps-install -S ${pkg}`,
      remove: (pkg) => `sudo xbps-remove ${pkg}`,
      update: () => `sudo xbps-install -Su`,
      search: (pkg) => `xbps-query -Rs ${pkg}`,
      info: (pkg) => `xbps-query -S ${pkg}`,
      list: () => `xbps-query -l`,
      clean: () => `sudo xbps-remove -O`,
    },
    homepage: 'https://github.com/void-linux/xbps',
  },

  // ─── GENTOO ───────────────────────────────────────────────────────────────
  {
    id: 'portage',
    name: 'portage',
    fullName: 'Gentoo Portage (emerge)',
    os: ['linux'],
    distros: ['Gentoo Linux', 'Funtoo', 'Calculate Linux'],
    icon: '🐧',
    color: '#54487a',
    detectCmd: 'which emerge',
    commands: {
      install: (pkg) => `sudo emerge ${pkg}`,
      remove: (pkg) => `sudo emerge --depclean ${pkg}`,
      update: () => `sudo emerge --sync`,
      upgrade: () => `sudo emerge -uDN @world`,
      search: (pkg) => `emerge --search ${pkg}`,
      info: (pkg) => `emerge --info ${pkg}`,
      list: () => `qlist -I`,
      clean: () => `sudo emerge --depclean`,
    },
    homepage: 'https://wiki.gentoo.org/wiki/Portage',
  },

  // ─── SLACKWARE ───────────────────────────────────────────────────────────
  {
    id: 'slackpkg',
    name: 'slackpkg',
    fullName: 'Slackware Package Manager',
    os: ['linux'],
    distros: ['Slackware'],
    icon: '📁',
    color: '#2a2a8a',
    detectCmd: 'which slackpkg',
    commands: {
      install: (pkg) => `sudo slackpkg install ${pkg}`,
      remove: (pkg) => `sudo slackpkg remove ${pkg}`,
      update: () => `sudo slackpkg update`,
      upgrade: () => `sudo slackpkg upgrade-all`,
      search: (pkg) => `slackpkg search ${pkg}`,
      info: (pkg) => `slackpkg info ${pkg}`,
    },
    homepage: 'https://www.slackpkg.org/',
  },

  // ─── SABAYON / ENTROPY ──────────────────────────────────────────────────
  {
    id: 'entropy',
    name: 'equo',
    fullName: 'Entropy Package Manager (Sabayon)',
    os: ['linux'],
    distros: ['Sabayon Linux'],
    icon: '⚗️',
    color: '#5a0fa0',
    detectCmd: 'which equo',
    commands: {
      install: (pkg) => `sudo equo install ${pkg}`,
      remove: (pkg) => `sudo equo remove ${pkg}`,
      update: () => `sudo equo update`,
      upgrade: () => `sudo equo upgrade`,
      search: (pkg) => `equo search ${pkg}`,
      list: () => `equo list installed`,
    },
    homepage: 'https://wiki.sabayon.org/index.php?title=En:Entropy',
  },

  // ─── NIX ─────────────────────────────────────────────────────────────────
  {
    id: 'nix',
    name: 'nix',
    fullName: 'Nix Package Manager',
    os: ['linux', 'macos', 'cross'],
    distros: ['NixOS', 'Any (multi-platform)'],
    icon: '❄️',
    color: '#5277c3',
    detectCmd: 'which nix',
    commands: {
      install: (pkg) => `nix-env -iA nixpkgs.${pkg}`,
      remove: (pkg) => `nix-env -e ${pkg}`,
      update: () => `nix-channel --update`,
      upgrade: () => `nix-env -u`,
      search: (pkg) => `nix search nixpkgs ${pkg}`,
      info: (pkg) => `nix-env -qa --description | grep ${pkg}`,
      list: () => `nix-env -q`,
      clean: () => `nix-collect-garbage -d`,
    },
    homepage: 'https://nixos.org/nix/',
  },
  {
    id: 'nixos',
    name: 'nixos-rebuild',
    fullName: 'NixOS System Rebuild',
    os: ['linux'],
    distros: ['NixOS'],
    icon: '🔷',
    color: '#5277c3',
    detectCmd: 'which nixos-rebuild',
    commands: {
      upgrade: () => `sudo nixos-rebuild switch --upgrade`,
      install: (pkg) => `# Add to /etc/nixos/configuration.nix:\n# environment.systemPackages = with pkgs; [ ${pkg} ];\nsudo nixos-rebuild switch`,
      clean: () => `sudo nix-collect-garbage -d && sudo nixos-rebuild boot`,
    },
    homepage: 'https://nixos.org/',
  },

  // ─── GNU GUIX ────────────────────────────────────────────────────────────
  {
    id: 'guix',
    name: 'guix',
    fullName: 'GNU Guix Package Manager',
    os: ['linux', 'cross'],
    distros: ['GNU Guix System', 'Any GNU/Linux'],
    icon: '🐃',
    color: '#a80030',
    detectCmd: 'which guix',
    commands: {
      install: (pkg) => `guix install ${pkg}`,
      remove: (pkg) => `guix remove ${pkg}`,
      update: () => `guix pull`,
      upgrade: () => `guix upgrade`,
      search: (pkg) => `guix search ${pkg}`,
      info: (pkg) => `guix show ${pkg}`,
      list: () => `guix package -I`,
      clean: () => `guix gc`,
    },
    homepage: 'https://guix.gnu.org/',
  },

  // ─── FLATPAK ─────────────────────────────────────────────────────────────
  {
    id: 'flatpak',
    name: 'flatpak',
    fullName: 'Flatpak (Sandboxed Packages)',
    os: ['linux'],
    distros: ['Any Linux'],
    icon: '📦',
    color: '#4a86cf',
    detectCmd: 'which flatpak',
    commands: {
      install: (pkg) => `flatpak install flathub ${pkg}`,
      remove: (pkg) => `flatpak uninstall ${pkg}`,
      update: () => `flatpak update`,
      search: (pkg) => `flatpak search ${pkg}`,
      info: (pkg) => `flatpak info ${pkg}`,
      list: () => `flatpak list`,
      clean: () => `flatpak uninstall --unused`,
    },
    homepage: 'https://flatpak.org/',
  },

  // ─── SNAP ────────────────────────────────────────────────────────────────
  {
    id: 'snap',
    name: 'snap',
    fullName: 'Snap (Canonical)',
    os: ['linux'],
    distros: ['Ubuntu', 'Any Snapd-enabled'],
    icon: '🔩',
    color: '#e95420',
    detectCmd: 'which snap',
    commands: {
      install: (pkg) => `sudo snap install ${pkg}`,
      remove: (pkg) => `sudo snap remove ${pkg}`,
      update: () => `sudo snap refresh`,
      search: (pkg) => `snap find ${pkg}`,
      info: (pkg) => `snap info ${pkg}`,
      list: () => `snap list`,
    },
    homepage: 'https://snapcraft.io/',
  },

  // ─── APPIMAGE ────────────────────────────────────────────────────────────
  {
    id: 'appimage',
    name: 'AppImage',
    fullName: 'AppImage (Portable Format)',
    os: ['linux'],
    distros: ['Any Linux'],
    icon: '🖼️',
    color: '#21a038',
    detectCmd: null,
    commands: {
      install: (pkg) => `chmod +x ${pkg}.AppImage && ./${pkg}.AppImage`,
      info: (pkg) => `# Download from https://appimage.github.io/apps/`,
    },
    homepage: 'https://appimage.org/',
  },

  // ─── macOS ────────────────────────────────────────────────────────────────
  {
    id: 'brew',
    name: 'Homebrew',
    fullName: 'Homebrew (macOS/Linux)',
    os: ['macos', 'linux'],
    distros: ['macOS', 'Linux (brew on Linux)'],
    icon: '🍺',
    color: '#fbb040',
    detectCmd: 'which brew',
    commands: {
      install: (pkg) => `brew install ${pkg}`,
      remove: (pkg) => `brew uninstall ${pkg}`,
      update: () => `brew update`,
      upgrade: () => `brew upgrade`,
      search: (pkg) => `brew search ${pkg}`,
      info: (pkg) => `brew info ${pkg}`,
      list: () => `brew list`,
      clean: () => `brew cleanup`,
    },
    homepage: 'https://brew.sh/',
  },
  {
    id: 'macports',
    name: 'MacPorts',
    fullName: 'MacPorts (formerly DarwinPorts)',
    os: ['macos'],
    distros: ['macOS'],
    icon: '⚓',
    color: '#2b5daa',
    detectCmd: 'which port',
    commands: {
      install: (pkg) => `sudo port install ${pkg}`,
      remove: (pkg) => `sudo port uninstall ${pkg}`,
      update: () => `sudo port selfupdate`,
      upgrade: () => `sudo port upgrade outdated`,
      search: (pkg) => `port search ${pkg}`,
      info: (pkg) => `port info ${pkg}`,
      list: () => `port installed`,
      clean: () => `sudo port reclaim`,
    },
    homepage: 'https://www.macports.org/',
  },
  {
    id: 'mas',
    name: 'mas',
    fullName: 'Mac App Store CLI',
    os: ['macos'],
    distros: ['macOS'],
    icon: '🍎',
    color: '#000',
    detectCmd: 'which mas',
    commands: {
      install: (pkg) => `mas install ${pkg}`,
      upgrade: () => `mas upgrade`,
      search: (pkg) => `mas search ${pkg}`,
      info: (pkg) => `mas info ${pkg}`,
      list: () => `mas list`,
    },
    homepage: 'https://github.com/mas-cli/mas',
  },

  // ─── BSD ──────────────────────────────────────────────────────────────────
  {
    id: 'pkg',
    name: 'pkg',
    fullName: 'FreeBSD pkg',
    os: ['bsd'],
    distros: ['FreeBSD', 'GhostBSD'],
    icon: '😈',
    color: '#ab2b28',
    detectCmd: 'which pkg',
    commands: {
      install: (pkg) => `sudo pkg install ${pkg}`,
      remove: (pkg) => `sudo pkg delete ${pkg}`,
      update: () => `sudo pkg update`,
      upgrade: () => `sudo pkg upgrade`,
      search: (pkg) => `pkg search ${pkg}`,
      info: (pkg) => `pkg info ${pkg}`,
      list: () => `pkg info`,
      clean: () => `sudo pkg autoremove`,
    },
    homepage: 'https://www.freebsd.org/cgi/man.cgi?pkg(8)',
  },
  {
    id: 'pkgsrc',
    name: 'pkgsrc',
    fullName: 'NetBSD pkgsrc',
    os: ['bsd', 'cross'],
    distros: ['NetBSD', 'DragonFly BSD', 'macOS', 'Solaris'],
    icon: '🔱',
    color: '#f26522',
    detectCmd: 'which pkgin',
    commands: {
      install: (pkg) => `sudo pkgin install ${pkg}`,
      remove: (pkg) => `sudo pkgin remove ${pkg}`,
      update: () => `sudo pkgin update`,
      upgrade: () => `sudo pkgin upgrade`,
      search: (pkg) => `pkgin search ${pkg}`,
      info: (pkg) => `pkgin show-full-deps ${pkg}`,
      list: () => `pkgin list`,
    },
    homepage: 'https://www.pkgsrc.org/',
  },
  {
    id: 'openbsd-pkg',
    name: 'pkg_add',
    fullName: 'OpenBSD pkg_add',
    os: ['bsd'],
    distros: ['OpenBSD'],
    icon: '🐡',
    color: '#f7a709',
    detectCmd: 'which pkg_add',
    commands: {
      install: (pkg) => `sudo pkg_add ${pkg}`,
      remove: (pkg) => `sudo pkg_delete ${pkg}`,
      update: () => `sudo pkg_add -u`,
      search: (pkg) => `pkg_info -Q ${pkg}`,
      info: (pkg) => `pkg_info ${pkg}`,
      list: () => `pkg_info`,
    },
    homepage: 'https://man.openbsd.org/pkg_add',
  },

  // ─── WINDOWS ─────────────────────────────────────────────────────────────
  {
    id: 'winget',
    name: 'winget',
    fullName: 'Windows Package Manager',
    os: ['windows'],
    distros: ['Windows 10/11'],
    icon: '🪟',
    color: '#0078d4',
    detectCmd: 'where winget',
    commands: {
      install: (pkg) => `winget install ${pkg}`,
      remove: (pkg) => `winget uninstall ${pkg}`,
      update: () => `winget upgrade`,
      upgrade: () => `winget upgrade --all`,
      search: (pkg) => `winget search ${pkg}`,
      info: (pkg) => `winget show ${pkg}`,
      list: () => `winget list`,
    },
    homepage: 'https://learn.microsoft.com/en-us/windows/package-manager/',
  },
  {
    id: 'choco',
    name: 'Chocolatey',
    fullName: 'Chocolatey Package Manager',
    os: ['windows'],
    distros: ['Windows'],
    icon: '🍫',
    color: '#80250d',
    detectCmd: 'where choco',
    commands: {
      install: (pkg) => `choco install ${pkg} -y`,
      remove: (pkg) => `choco uninstall ${pkg} -y`,
      update: () => `choco upgrade all`,
      search: (pkg) => `choco search ${pkg}`,
      info: (pkg) => `choco info ${pkg}`,
      list: () => `choco list --local-only`,
      clean: () => `choco optimize --reduce-nupkg-only`,
    },
    homepage: 'https://chocolatey.org/',
  },
  {
    id: 'scoop',
    name: 'Scoop',
    fullName: 'Scoop (Windows)',
    os: ['windows'],
    distros: ['Windows'],
    icon: '🥄',
    color: '#1d4c79',
    detectCmd: 'where scoop',
    commands: {
      install: (pkg) => `scoop install ${pkg}`,
      remove: (pkg) => `scoop uninstall ${pkg}`,
      update: () => `scoop update`,
      upgrade: () => `scoop update *`,
      search: (pkg) => `scoop search ${pkg}`,
      info: (pkg) => `scoop info ${pkg}`,
      list: () => `scoop list`,
      clean: () => `scoop cleanup *`,
    },
    homepage: 'https://scoop.sh/',
  },

  // ─── LANGUAGE-SPECIFIC ───────────────────────────────────────────────────
  {
    id: 'pip',
    name: 'pip',
    fullName: 'Python Package Installer',
    os: ['cross', 'linux', 'macos', 'windows'],
    distros: ['Any (Python required)'],
    icon: '🐍',
    color: '#3776ab',
    detectCmd: 'which pip3',
    commands: {
      install: (pkg) => `pip install ${pkg}`,
      remove: (pkg) => `pip uninstall ${pkg}`,
      upgrade: () => `pip list --outdated | cut -d' ' -f1 | xargs pip install -U`,
      search: (pkg) => `pip index versions ${pkg}`,
      info: (pkg) => `pip show ${pkg}`,
      list: () => `pip list`,
      clean: () => `pip cache purge`,
    },
    homepage: 'https://pip.pypa.io/',
  },
  {
    id: 'npm',
    name: 'npm',
    fullName: 'Node Package Manager',
    os: ['cross'],
    distros: ['Any (Node.js required)'],
    icon: '📦',
    color: '#cb3837',
    detectCmd: 'which npm',
    commands: {
      install: (pkg) => `npm install ${pkg}`,
      remove: (pkg) => `npm uninstall ${pkg}`,
      upgrade: () => `npm update`,
      search: (pkg) => `npm search ${pkg}`,
      info: (pkg) => `npm info ${pkg}`,
      list: () => `npm list -g`,
      clean: () => `npm cache clean --force`,
    },
    homepage: 'https://npmjs.com/',
  },
  {
    id: 'yarn',
    name: 'Yarn',
    fullName: 'Yarn Package Manager',
    os: ['cross'],
    distros: ['Any (Node.js required)'],
    icon: '🧶',
    color: '#2c8ebb',
    detectCmd: 'which yarn',
    commands: {
      install: (pkg) => `yarn add ${pkg}`,
      remove: (pkg) => `yarn remove ${pkg}`,
      upgrade: () => `yarn upgrade`,
      search: (pkg) => `# Use: https://yarnpkg.com/package/${pkg}`,
      info: (pkg) => `yarn info ${pkg}`,
      list: () => `yarn global list`,
      clean: () => `yarn cache clean`,
    },
    homepage: 'https://yarnpkg.com/',
  },
  {
    id: 'cargo',
    name: 'cargo',
    fullName: "Rust's Package Manager",
    os: ['cross'],
    distros: ['Any (Rust required)'],
    icon: '⚙️',
    color: '#b7410e',
    detectCmd: 'which cargo',
    commands: {
      install: (pkg) => `cargo install ${pkg}`,
      remove: (pkg) => `cargo uninstall ${pkg}`,
      upgrade: () => `cargo install-update -a`,
      search: (pkg) => `cargo search ${pkg}`,
      info: (pkg) => `cargo info ${pkg}`,
      list: () => `cargo install --list`,
    },
    homepage: 'https://doc.rust-lang.org/cargo/',
  },
  {
    id: 'gem',
    name: 'gem',
    fullName: 'RubyGems',
    os: ['cross'],
    distros: ['Any (Ruby required)'],
    icon: '💎',
    color: '#cc342d',
    detectCmd: 'which gem',
    commands: {
      install: (pkg) => `gem install ${pkg}`,
      remove: (pkg) => `gem uninstall ${pkg}`,
      upgrade: () => `gem update`,
      search: (pkg) => `gem search ${pkg}`,
      info: (pkg) => `gem info ${pkg}`,
      list: () => `gem list`,
      clean: () => `gem cleanup`,
    },
    homepage: 'https://rubygems.org/',
  },
  {
    id: 'composer',
    name: 'Composer',
    fullName: 'PHP Composer',
    os: ['cross'],
    distros: ['Any (PHP required)'],
    icon: '🎼',
    color: '#885630',
    detectCmd: 'which composer',
    commands: {
      install: (pkg) => `composer require ${pkg}`,
      remove: (pkg) => `composer remove ${pkg}`,
      upgrade: () => `composer update`,
      search: (pkg) => `composer search ${pkg}`,
      info: (pkg) => `composer show ${pkg}`,
      list: () => `composer show`,
    },
    homepage: 'https://getcomposer.org/',
  },
  {
    id: 'go',
    name: 'go get',
    fullName: 'Go Modules',
    os: ['cross'],
    distros: ['Any (Go required)'],
    icon: '🐹',
    color: '#00add8',
    detectCmd: 'which go',
    commands: {
      install: (pkg) => `go install ${pkg}@latest`,
      upgrade: () => `go get -u ./...`,
      info: (pkg) => `go list -m ${pkg}`,
      list: () => `go list -m all`,
    },
    homepage: 'https://pkg.go.dev/',
  },
  {
    id: 'nuget',
    name: 'NuGet',
    fullName: 'NuGet (.NET)',
    os: ['cross', 'windows'],
    distros: ['Any (.NET required)'],
    icon: '🔷',
    color: '#004880',
    detectCmd: 'which dotnet',
    commands: {
      install: (pkg) => `dotnet add package ${pkg}`,
      remove: (pkg) => `dotnet remove package ${pkg}`,
      upgrade: () => `dotnet list package --outdated`,
      search: (pkg) => `dotnet package search ${pkg}`,
      info: (pkg) => `dotnet list package | grep ${pkg}`,
      list: () => `dotnet list package`,
    },
    homepage: 'https://www.nuget.org/',
  },
  {
    id: 'conda',
    name: 'conda',
    fullName: 'Conda (Anaconda/Miniconda)',
    os: ['cross'],
    distros: ['Any (Conda required)'],
    icon: '🐍',
    color: '#44a833',
    detectCmd: 'which conda',
    commands: {
      install: (pkg) => `conda install ${pkg}`,
      remove: (pkg) => `conda remove ${pkg}`,
      update: () => `conda update conda`,
      upgrade: () => `conda update --all`,
      search: (pkg) => `conda search ${pkg}`,
      info: (pkg) => `conda info ${pkg}`,
      list: () => `conda list`,
      clean: () => `conda clean --all`,
    },
    homepage: 'https://conda.io/',
  },
  {
    id: 'maven',
    name: 'Maven',
    fullName: 'Apache Maven',
    os: ['cross'],
    distros: ['Any (Java required)'],
    icon: '☕',
    color: '#c71a36',
    detectCmd: 'which mvn',
    commands: {
      install: (pkg) => `# Add to pom.xml:\n# <dependency>\n#   <groupId>GROUP</groupId>\n#   <artifactId>${pkg}</artifactId>\n# </dependency>\nmvn install`,
      info: (pkg) => `mvn dependency:resolve -Dartifact=${pkg}`,
      list: () => `mvn dependency:list`,
    },
    homepage: 'https://maven.apache.org/',
  },
]

/**
 * OS Detection heuristics — runs in browser environment
 */
export function detectOS() {
  // Prefer modern userAgentData (Chrome 90+, Edge 90+) over deprecated navigator.platform
  const platformHint = navigator.userAgentData?.platform || navigator.platform || ''
  const ua = navigator.userAgent

  if (/Win/i.test(platformHint) || /Windows/i.test(ua)) return 'windows'
  if (/Mac|iPhone|iPad/i.test(platformHint) || /Macintosh/i.test(ua)) return 'macos'
  if (/Linux/i.test(platformHint) || /Linux/i.test(ua)) return 'linux'
  if (/FreeBSD/i.test(ua) || /OpenBSD/i.test(ua) || /NetBSD/i.test(ua)) return 'bsd'

  return 'cross'
}

/**
 * Get managers for detected/selected OS, sorted by priority
 */
export function getManagersForOS(osId) {
  return PACKAGE_MANAGERS.filter(
    (m) => m.os.includes(osId) || m.os.includes('cross')
  )
}

export function getManagerById(id) {
  return PACKAGE_MANAGERS.find((m) => m.id === id)
}

// Priority managers per OS (shown first in selector)
export const OS_DEFAULTS = {
  linux: ['apt', 'dnf', 'pacman', 'zypper', 'apk', 'xbps', 'portage'],
  macos: ['brew', 'macports', 'mas'],
  windows: ['winget', 'choco', 'scoop'],
  bsd: ['pkg', 'pkgsrc', 'openbsd-pkg'],
  cross: ['nix', 'flatpak', 'snap', 'pip', 'npm', 'cargo'],
}
